spring:
  application:
    name: gateway-service

  profiles:
    active: dev



# 유레카에 gateway 등록
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka



# 게이트 웨이 포트
server:
  port: 9777

jwt:
  header: Authorization
  secret: vzxvgsjdgdfjgfdskgjdsfkgjdsfkgkdsfgjdfkgjdfsgdklgjadgslkjgsaklj
  token-validity-in-seconds: 86400 # ttl (?)


---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: local
