spring:
  application:
    name: gateway-service

  profiles:
    active: dev

  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2



# 유레카에 gateway 등록
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

# 게이트 웨이 포트
server:
  port: 9777


management:
  endpoints:
    web:
      exposure:
        include: health,info,pause,resume
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: local

nhn:
  cloud:
    keyManager:
      appkey: 2SxwmBzUfnqJaA2A
      redisKey: 83d9f2929dc849fb89bee961250b1676
      jwtKey: d9743d803f0441ffa8e242032647db41
      userAccessKey: J9VxQFQEsmerR1n7FeJ6
      secretAccessKey: zZEVopUHt6dxgRMt
