spring:
  main:
    web-application-type: reactive

  application:
    name: gateway


  cloud:
    gateway:
        routes:
          - id: store
            uri: lb://STORE
            predicates:
                  - Path=/api/v1/store/**

          - id: coupon
            uri: http://localhost:8070
            predicates:
                  - Path=/api/v1/coupon/**



# 유레카에 gateway 등록
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


# 게이트 웨이 포트
server:
  port: 8089


