cor:
  url: https://novabook.store

nhn:
  cloud:
    keyManager:
      appkey: 2SxwmBzUfnqJaA2A
      redisKey: 83d9f2929dc849fb89bee961250b1676
      jwtKey: d9743d803f0441ffa8e242032647db41
      userAccessKey: J9VxQFQEsmerR1n7FeJ6
      secretAccessKey: zZEVopUHt6dxgRMt
